version: '3'
services:
  attendees-http:
    image: jpgough/attendees:latest
    ports:
      - "80:8080"
      - "9090:9090"
  meetings-http:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "jpgough/meetings:latest"
    ports:
      - "8081:8081"